import movieDb from '../movieDbService/movieDbApi.js';
import refs from './refs.js';
const { VideoPostApi, AudioPostApi, ImagePostApi, TextPostApi } = movieDb;
const { videoPost, audioPost, imagePost, textPost } = refs;
const videoPostApi = new VideoPostApi();
const audioPostApi = new AudioPostApi();
const imagePostApi = new ImagePostApi();
const textPostApi = new TextPostApi();
videoPostApi.createPostMarckup(videoPost, 0);
audioPostApi.createPostMarckup(audioPost, 1);
imagePostApi.createPostMarckup(imagePost, 2);
textPostApi.createPostMarckup(textPost, 3);
